### ISSUE TITLE
CAMELS URL changed

### ISSUE THREAD

**Issue by kongdd** [scantle/caRmels#1]
CAMELS URL changed:

From: http://ral.ucar.edu/sites/default/files/public/product-tool/camels-catchment-attributes-and-meteorology-for-large-sample-studies-dataset-downloads/,
To: https://gdex.ucar.edu/dataset/camels.html.

The function download CAMELS will be error:

https://github.com/scantle/caRmels/blob/353e749775597e20ea724ff4fd96ba0af7dcaf69/R/downloadCAMELS.R#L1-L10

**Comment by scantle** [comment]
Thanks for letting me know! Fixed by 40f247d

**Comment by kongdd** [comment]
Thanks for your quick action.
